# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d41852612abaab3289197a10b0b4bf33e12977029cbf8ce1bf6bf3acf87efeb5845ea3614c333987a0c1d805196b1e8c6f26a18ddeda0695ded6dc0c8b2808f3

test:
  secret_key_base: 6ad12ecff491fb26f7cd5264f5d60688e93205cb06df5b35d19ce2f51c94a86da3c172a1b89a56a16beadc16962f7bb7f6e86ffe4b656b5b75262a9880a580e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
